apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsnstopics.aws.notification.example.org
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: notification.example.org/v1alpha1
    kind: XSNSTopic
  resources:
    - name: snstopic
      base:
        apiVersion: sns.aws.crossplane.io/v1beta1
        kind: Topic
        metadata:
          labels: 
            env: prod
          name: some-topic
        spec:
          forProvider:
            region: us-east-1
            name: sample-topic
        patches:
          - fromFieldPath: "spec.parameters.name"
            toFieldPath: "spec.forProvider.displayName"
    - name: snssubscription
      base:
        apiVersion: sns.aws.crossplane.io/v1beta1
        kind: Subscription
        metadata:
          name: subscription1
        spec:
          forProvider:
            region: us-east-1
            name: subscription1
            protocol: email
            endpoint: kaushik287@gmail.com
            topicArnSelector:
              matchControllerRef: true 
              matchLabels: 
                env: prod